version: "3.9"

services:
  controller:
    build: ./controller
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./controller:/app
    command: sh -c "python flower_server.py & uvicorn api:app --host 0.0.0.0 --port 8000 --reload"

  uav1:
    build: ./uav
    environment:
      - CONTROLLER_URL=http://controller:8000
      - FLOWER_SERVER=controller:8080
      - IMG_RANGE=[1,100]
    volumes:
      - ./uav:/app
      - ./configs/uav1.json:/config/uav_config.json
      - ${IMG_PATH}:/cam_feed
      - ${DATASET_PATH}:/dataset:ro
      - ./Model/fire_model.onnx:/app/best_model.onnx:ro

  uav2:
    build: ./uav
    environment:
      - CONTROLLER_URL=http://controller:8000
      - FLOWER_SERVER=controller:8080
      - IMG_RANGE=[100,200]
    volumes:
      - ./uav:/app
      - ./configs/uav2.json:/config/uav_config.json
      - ${IMG_PATH}:/cam_feed
      - ${DATASET_PATH}:/dataset:ro
      - ./Model/fire_model.onnx:/app/best_model.onnx:ro